server:
  port: 8082
jasypt:
  encryptor:
    bean: encryptorBean
spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mariadb://dop0617-shop-maria103dialect.ctfsm3aapnnp.ap-northeast-2.rds.amazonaws.com:3306/shallwe
    username: ENC(tB5rllJdNVCnHIgiYnIZ+nfS5yhqBCYag0q+egT4pS+UngjSmOK7aacPO0/ObecK)
    password: ENC(k0SQ5Ypj/86aDM+snjlgI5Ox+3OAgu7Xh6db6y6L3ikLMFcD7jNfxfZtrhfNlcnT)
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none  #create , create-drop , update , validate, none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MariaDB103Dialect