server:
  port: 8082
spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mariadb://dop0617-shop-maria103dialect.ctfsm3aapnnp.ap-northeast-2.rds.amazonaws.com:3306/shallwe
    username: admin
    password: yh7839205!
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MariaDB104Dialect
      ddl-auto: none  #create , create-drop , update , validate, none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
