server:
  port: 8082
spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mariadb://rds-dop0617.ctfsm3aapnnp.ap-northeast-2.rds.amazonaws.com:3306/shallwe
    username: root
    password: yh7839205!
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create  #create , create-drop , update , validate, none
    properties:
      hibernate:
        show_sql: true
        format_sql: true